export const COACH_LOGIN_REQUEST = 'COACH_LOGIN_REQUEST'
export const COACH_LOGIN_SUCCESS = 'COACH_LOGIN_SUCCESS'
export const COACH_LOGIN_FAIL = 'COACH_LOGIN_FAIL'
export const COACH_LOGOUT = 'COACH_LOOUT'

export const COACH_DETAILS_REQUEST = 'COACH_DETAILS_REQUEST'
export const COACH_DETAILS_SUCCESS = 'COACH_DETAILS_SUCCESS'
export const COACH_DETAILS_FAIL = 'COACH_DETAILS_FAIL'
export const COACH_DETAILS_RESET = 'COACH_DETAILS_RESET'

export const COACH_UPDATE_PROFILE_REQUEST = 'COACH_UPDATE_PROFILE_REQUEST'
export const COACH_UPDATE_PROFILE_SUCCESS = 'COACH_UPDATE_PROFILE_SUCCESS'
export const COACH_UPDATE_PROFILE_FAIL = 'COACH_UPDATE_PROFILE_FAIL'
export const COACH_UPDATE_PROFILE_RESET = 'COACH_UPDATE_PROFILE_RESET'

export const COACH_LIST_REQUEST = 'COACH_LIST_REQUEST'
export const COACH_LIST_SUCCESS = 'COACH_LIST_SUCCESS'
export const COACH_LIST_FAIL = 'COACH_LIST_FAIL'

export const LIST_COACH_DETAILS_REQUEST = 'LIST_COACH_DETAILS_REQUEST'
export const LIST_COACH_DETAILS_SUCCESS = 'LIST_COACH_DETAILS_SUCCESS'
export const LIST_COACH_DETAILS_FAIL = 'LIST_COACH_DETAILS_FAIL'

export const COACH_CREATE_REVIEW_REQUEST = 'COACH_CREATE_REVIEW_REQUEST'
export const COACH_CREATE_REVIEW_SUCCESS = 'COACH_CREATE_REVIEW_SUCCESS'
export const COACH_CREATE_REVIEW_FAIL = 'COACH_CREATE_REVIEW_FAIL'
export const COACH_CREATE_REVIEW_RESET = 'COACH_CREAT_REVIEW_RESET'

export const COACH_REGISTER_REQUEST = 'COACH_REGISTER_REQUEST'
export const COACH_REGISTER_SUCCESS = 'COACH_REGISTER_SUCCESS'
export const COACH_REGISTER_FAIL = 'COACH_REGISTER_FAIL'

export const COACH_DELETE_REQUEST = 'COACH_DELETE_REQUEST'
export const COACH_DELETE_SUCCESS = 'COACH_DELETE_SUCCESS'
export const COACH_DELETE_FAIL = 'COACH_DELETE_FAIL'
