export const COACH_LOGIN_REQUEST = 'COACH_LOGIN_REQUEST'
export const COACH_LOGIN_SUCCESS = 'COACH_LOGIN_SUCCESS'
export const COACH_LOGIN_FAIL = 'COACH_LOGIN_FAIL'
export const COACH_LOGOUT = 'COACH_LOOUT'
