export const COACH_LOGIN_REQUEST = 'COACH_LOGIN_REQUEST'
export const COACH_LOGIN_SUCCESS = 'COACH_LOGIN_SUCCESS'
export const COACH_LOGIN_FAIL = 'COACH_LOGIN_FAIL'
export const COACH_LOGOUT = 'COACH_LOOUT'

export const COACH_DETAILS_REQUEST = 'COACH_DETAILS_REQUEST'
export const COACH_DETAILS_SUCCESS = 'COACH_DETAILS_SUCCESS'
export const COACH_DETAILS_FAIL = 'COACH_DETAILS_FAIL'

export const COACH_UPDATE_PROFILE_REQUEST = 'COACH_UPDATE_PROFILE_REQUEST'
export const COACH_UPDATE_PROFILE_SUCCESS = 'COACH_UPDATE_PROFILE_SUCCESS'
export const COACH_UPDATE_PROFILE_FAIL = 'COACH_UPDATE_PROFILE_FAIL'
export const COACH_UPDATE_PROFILE_RESET = 'COACH_UPDATE_PROFILE_RESET'
