export const PROGRAM_LIST_REQUEST = 'PROGRAM_LIST_REQUEST'
export const PROGRAM_LIST_SUCCESS = 'PROGRAM_LIST_SUCCESS'
export const PROGRAM_LIST_FAIL = 'PROGRAM_LIST_FAIL'

export const PROGRAM_DETAILS_REQUEST = 'PROGRAM_DETAILS_REQUEST'
export const PROGRAM_DETAILS_SUCCESS = 'PROGRAM_DETAILS_SUCCESS'
export const PROGRAM_DETAILS_FAIL = 'PROGRAM_DETAILS_FAIL'
