export const WORKOUT_CREATE_REQUEST = 'WORKOUT_CREATE_REQUEST'
export const WORKOUT_CREATE_SUCCESS = 'WORKOUT_CREATE_SUCCESS'
export const WORKOUT_CREATE_FAIL = 'WORKOUT_CREATE_FAIL'
export const WORKOUT_CREATE_RESET = 'WORKOUT_CREATE_RESET'

export const WORKOUT_LIST_REQUEST = 'WORKOUT_LIST_REQUEST'
export const WORKOUT_LIST_SUCCESS = 'WORKOUT_LIST_SUCCESS'
export const WORKOUT_LIST_FAIL = 'WORKOUT_LIST_FAIL'
export const WORKOUT_LIST_RESET = 'WORKOUT_LIST_RESET'
