export const WORKOUT_CREATE_REQUEST = 'WORKOUT_CREATE_REQUEST'
export const WORKOUT_CREATE_SUCCESS = 'WORKOUT_CREATE_SUCCESS'
export const WORKOUT_CREATE_FAIL = 'WORKOUT_CREATE_FAIL'
export const WORKOUT_CREATE_RESET = 'WORKOUT_CREATE_RESET'
